---
# Destroy KVM domains for K8s cluster
# author: Mau
# check more in https://github.com/cloud-native-everything/srlinux-ansible-lab
# June 2021
#
#
- hosts: 10.5.0.104 
  gather_facts: no
  remote_user: root


  pre_tasks:
    - include_vars: "/srl-lab/cfg/{{ cfg_option }}/global_vars.yml" 

  tasks:

    - name: Get management BRIDGE for the recently created leaf/spine instances
      shell: brctl show | grep 'br-' | grep 'veth' | awk '{print $1}'
      register: mgmt_br
      changed_when: False

#    - name: Check if management BRIDGE exists
#      fail:
#        msg: "There is no management BRIDGE. Have you created the srl containerlab?"
#      when: mgmt_br.stdout == ""

    - name: Store bridge in mgmt_bridge var
      set_fact:
        mgmt_bridge: "{{ mgmt_br.stdout }}"

    - name: Check management BRIDGE
      debug:
        msg: "bridge is: {{ mgmt_bridge }}"


    - include: /srl-lab/servers/destroy-infra-services.yml
    - include: /srl-lab/servers/destroy-kvm-domains.yml 
    - include: /srl-lab/servers/destroy-veth-tcmirred-settings.yml
