---
# Create KVM domains for K8s cluster
# author: Mau
# email: pinrojas@gmail.com
# check more in https://github.com/cloud-native-everything/srlinux-ansible-lab
# June 2021
#
#
- hosts: 10.5.0.104 
  gather_facts: no
  remote_user: root

  vars:
    mgmt_bridge: "br-89bc9d566618"

  pre_tasks:
    - include_vars: "/srl-lab/cfg/{{ cfg_option }}/global_vars.yml" 

  tasks:

# Creating tap interfaces nad bridges 
#
    - include: /srl-lab/tap_interfaces_and_bridges.yml
    - include: /srl-lab/kvm-domains.yml 
