---
# Add ethernet-1/10 to leaf
# author: Mau
# email: pinrojas@gmail.com
# check more in https://github.com/cloud-native-everything/srlinux-ansible-lab
# June 2021
#
#
- hosts: baremetals
  gather_facts: no
  remote_user: root

  tasks:

    - name: get list of srl leaf instances
      shell: "ip netns | grep leaf | awk '{print $1}'"
      register: leaf_inst
      changed_when: False

    - name: DEBUG
      debug:
        msg: "item: {{ item }}"
      with_items: '{{ leaf_inst.stdout_lines }}'

    - name: Copying certs files
      copy:
        src: "/srl-lab/certs/certs/{{ item }}"
        dest: "/tmp/{{ item }}"
        force: no
        backup: no
      with_items: 
        - 'client.crt'
        - 'client_key.pem'
        - 'rootCA.crt' 

    - name: Copying gnmi JSON files
      copy:
        src: "/srl-lab/srl-instances/{{ item }}"
        dest: "/tmp/{{ item }}"
        force: no
        backup: no
      with_items: 
        - 'mac-vrf1-add-interface-e10.json'
        - 'ethernet-10.json'

    - name: add interface ethernet-1/10 to leaf
      command: 
        cmd: gnmic set --tls-ca rootCA.crt --tls-cert client.crt --tls-key client_key.pem -a {{ item }}:57400 --username admin --password admin -e json_ietf --skip-verify --update-path /interface\[name\=ethernet-1/10\] --update-file ethernet-10.json
        chdir: '/tmp'
      with_items: "{{ leaf_inst.stdout_lines }}"

    - name: add interface ethernet-1/10 to mac-vrf1
      command: 
        cmd: gnmic set --tls-ca rootCA.crt --tls-cert client.crt --tls-key client_key.pem -a {{ item }}:57400 --username admin --password admin -e json_ietf --skip-verify --update-path /interface\[name\=ethernet-1/3\] --update-file ethernet-10.json
        chdir: '/tmp'
      with_items: "{{ leaf_inst.stdout_lines }}"

