---
# Destroying netns
#

    - name: DELETE netns symbolic links for k8s instances
      file:
        path: "/var/run/netns/qemu-{{ item.name }}"
        state: absent
      with_items: "{{ k8s_inst }}"
