---
# Destroying netns
#

    - name: DELETE netns symbolic links for k8s instances
      file:
        path: "/var/run/netns/qemu-{{ item.name }}"
        state: absent
      with_items: "{{ k8s_inst }}"

    - name: DELETE multiple files and authorized_keys files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - '/tmp/net-qemu-container.sh'
        - '/tmp/tc_mirred.sh'
