---
# Creating tap interfaces nad bridges
#
    - name: Copying fss-net-qemu-container for qemu containers
      copy:
        src: 'fss-net-qemu-container.sh'
        dest: "/tmp/fss-net-qemu-container.sh"
        force: no
        mode: 755

    - name: Copying fss tc mirred scripts for qemu containers
      copy:
        src: 'fss_tc_mirred.sh'
        dest: "/tmp/fss_tc_mirred.sh"
        force: no
        mode: 755

    - name: Run the script fss-net-qemu-container for qemu containers
      shell: "/tmp/fss-net-qemu-container.sh {{ item.name }}"
      with_items: "{{ fss_inst }}"

    - name: Run the fss_tc_mirred.sh for qemu containers
      shell: "/tmp/fss_tc_mirred.sh qemu-{{ item.name }}"
      with_items: "{{ fss_inst }}"
