---
# Creating tap interfaces nad bridges 
#
    - name: Checking qemu containers namespaces
      shell: "ip netns exec $(ip netns | grep leaf1 | awk '{print $1}') ip link | grep e1-10 | awk '{print $2}' | cat"
      register: e10_present
      changed_when: False

    - name: Debug e10_present
      debug:
        msg: 'echo e10_present: {{ e10_present.stdout }}'

    - name: Copying net-qemu-container for qemu containers
      copy:
        src: 'net-qemu-container.sh'
        dest: "/tmp/net-qemu-container.sh"
        force: no
        mode: 755
      when:
        -  "'e1-10' not in e10_present.stdout"

    - name: Copying tc mirred scripts for qemu containers
      copy:
        src: 'tc_mirred.sh'
        dest: "/tmp/tc_mirred.sh"
        force: no
        mode: 755
      when:
        -  "'e1-10' not in e10_present.stdout"

    - name: Run the script net-qemu-container for qemu containers
      shell: "/tmp/net-qemu-container.sh {{ item.name }} {{ item.leaf }}"
      with_items: "{{ k8s_inst }}"
      when:
        -  "'e1-10' not in e10_present.stdout"

    - name: Run the tc_mirred.sh for qemu containers
      shell: "/tmp/tc_mirred.sh qemu-{{ item.name }}"
      with_items: "{{ k8s_inst }}"
      when:
        -  "'e1-10' not in e10_present.stdout"
