FROM python:3-alpine
RUN apk add --no-cache \
	bash \
	net-tools \
	tcpdump \
        curl \
        haproxy
COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
COPY readme.txt /
RUN echo 'its a test $(hostname)' > test.txt
