apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: 6.5.3.1
      peer-asn: 65221
      my-asn: 65201
    - peer-address: 6.5.3.2
      peer-asn: 65222
      my-asn: 65201
    - peer-address: 6.5.3.3
      peer-asn: 65223
      my-asn: 65201
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 192.168.110.0/24
